### ISSUE TITLE
DataFrames 0.20

### ISSUE THREAD

**Issue by xgdgsc** [xiaodaigh/JLBoost.jl#36]
```
(v1.3) pkg> add https://github.com/xiaodaigh/JLBoost.jl
  Updating git-repo `https://github.com/xiaodaigh/JLBoost.jl`
  Updating git-repo `https://github.com/xiaodaigh/JLBoost.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0] or uninstalled
 ├─restricted to versions 0.19 by JLBoost [13d6d4a1], leaving only versions 0.19.0-0.19.4
 │ └─JLBoost [13d6d4a1] log:
 │   ├─possible versions are: 0.1.3 or uninstalled
 │   └─JLBoost [13d6d4a1] is fixed to version 0.1.3
 └─restricted to versions 0.20.0 by an explicit requirement — no versions left
```

**Comment by xiaodaigh** [comment]
fixed by https://github.com/JuliaRegistries/General/pull/6468

You should be able to install JLBoost v1.3 later today or tomorrow and have DataFrames.jl v0.20 support

**Comment by xgdgsc** [comment]
Thanks. MLJJLBoost also?

**Comment by xiaodaigh** [comment]
> MLJJLBoost

See https://github.com/JuliaRegistries/General/pull/6566 

If no hiccup should be ready today or tomorrow.

Just a note, I am actively developing these and you may have noticed that i haven't started to market them too much yet because there are still many missing features, so I am just going to get them done before publicising. Publishing them is to make the testing and publishing process easier
